### ISSUE TITLE
Add Tests functionality

### ISSUE THREAD

**Issue by MikeAndrianov** [MikeAndrianov/easy_learning#11]
We need to add Tests to our project. 

In the **first version** implement next functionality:
- Ability to add new Tests by Lecturers and Admins(each question should have some answers, one of them must be correct) 
- Ability to path tests by Students
- Also add statistics after Tests(number of correct answers etc.)

Next resources might help you:
http://railscasts.com/episodes/196-nested-model-form-part-1
http://railscasts.com/episodes/197-nested-model-form-part-2
http://railscasts.com/episodes/196-nested-model-form-revised
http://railscasts.com/episodes/403-dynamic-forms

**Comment by MikeAndrianov** [comment]
Here is my point of view how should look new  form for Test creating. 
![result](https://f.cloud.github.com/assets/899220/2181440/d5ee127a-9750-11e3-874e-0ba1d70b4f55.png)

Our project built on Bootstrap 2. This is a documentation http://getbootstrap.com/2.3.2/base-css.html. Take a look here when you will develop this page

**Comment by ilyabyar** [comment]
I think, it is a good idea

2014-02-17 0:30 GMT+03:00 MikeAndrianov notifications@github.com:
