### ISSUE TITLE
Add Settings

### ISSUE THREAD

**Issue by MikeAndrianov** [MikeAndrianov/easy_learning#9]
Login as any User. Go to /user/settings. It's empty now here. Add  ability to change basic fields, such as
- [x]  Name (add this field to Users)
- [x]  Email
- [x]  Password
- [x] Contact phone (add this field to Users)
  etc.

Also you should **use validation** methods because we must to be ensure  that only valid data will be saved into our database. We should  prohibit leave empty fields such as _Name_, _Email_, _Password_ to Users. Validation errors should be presented on the top of the settings form.

**Comment by ilyabyar** [comment]
I will take this task

**Comment by ilyabyar** [comment]
I have done this task, except field Password

**Comment by ilyabyar** [comment]
Mike, you have to do the field called "Password" and the correct output of errors in fields.
